name: morakab-bazi

services:
  postgres:
    image: postgres:15.8
    container_name: morakab-bazi-postgres
    restart: unless-stopped
    ports:
      - "5477:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: morakab_bazi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
